## 1. Setup e imports

In [4]:
import sys
import pandas as pd
from dotenv import load_dotenv

# Raiz del proyecto (ejecutar desde notebooks/)
sys.path.append("../../")
load_dotenv("../../.env")
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)

from src.config.settings import COUNTRY
from src.core.scraper.app import ScrapingUtils
from src.core.scraper.url_filters import filter_product_urls
from src.core.price_tracking import run_price_tracking
from src.utils.clean_model_name import clean_model_name
from src.utils.replace_model_name import map_model_name, load_mapping_file
from src.core.italika_pipeline import build_price_comparison
from src.sources.sheets.reader import GoogleSheetReader

gsheets = GoogleSheetReader()
fr_scraper = ScrapingUtils()

## 2. Configuracion

In [ ]:
BRAND_NAME   = "Italika"
BRAND_URL    = "https://www.italika.mx/"
YEAR_SCRAPED = 2026

## Lectura de base de inventario

Lectura desde archivo local

In [ ]:
# CSV_PATH = rf"C:\Users\JTRUJILLO\Desktop\utiles\Reportes\historical_data\src\data\prices\{COUNTRY}-prices.csv"
# df_inventory = pd.read_csv(CSV_PATH)

Lectura desde archivo en google sheets

In [5]:
google_sheet_info = {
    "sheet_name": '[MKP - MX] Data',
    "worksheet": f'price_data',
}
df_inventory = gsheets.read_sheet(google_sheet_info)

## 3. Cargar inventario

In [ ]:
df_inventory = df_inventory[df_inventory["brand"] == BRAND_NAME]
df_inventory = df_inventory[df_inventory["status"].isin(["available", "no_stock"])] # Modelos disponibles en marketplace
df_inventory

,date,code,brand,model,year,status,price_base,discount_amount,price_net
125,06/04/2026,MX2589-italika-tc-300,Italika,TC 300,2025,available,47999.0,0.0,47999.0
192,06/04/2026,MX2987-italika-ws-175-sport-grafito,Italika,WS 175 Sport Grafito,2026,no_stock,27999.0,0.0,27999.0
217,06/04/2026,MX3395-italika-125z-gps,Italika,125Z GPS,2026,available,27999.0,0.0,27999.0
218,06/04/2026,MX1306-italika-dm-250,Italika,DM 250,2026,no_stock,33999.0,0.0,33999.0
244,06/04/2026,MX2769-italika-at-110-rt,Italika,AT 110 RT,2026,no_stock,18999.0,0.0,18999.0
...,...,...,...,...,...,...,...,...,...
1582,06/04/2026,MX2507-italika-280z,Italika,280Z,2026,no_stock,42999.0,0.0,42999.0
1610,06/04/2026,MX3410-italika-modena-175-gps,Italika,Modena 175 GPS,2026,available,32999.0,0.0,32999.0
1613,06/04/2026,MX3454-italika-firebird-300-gps,Italika,Firebird 300 GPS,2026,no_stock,43999.0,0.0,43999.0
1699,06/04/2026,MX3408-italika-ft-150-gts-gps,Italika,FT 150 GTS GPS,2026,available,24999.0,0.0,24999.0
1703,06/04/2026,MX3409-italika-ft-250-gts-gps,Italika,FT 250 GTS GPS,2026,available,36999.0,0.0,36999.0

## 4. Obtener URLs de cada modelo

In [4]:
# Descubrimiento dinamico de URLs desde el sitio
urls = fr_scraper.get_all_urls_from_website(BRAND_URL)
valid_urls = filter_product_urls(urls, exclude_terms=["morbidelli"])
print(f"URLs validas encontradas: {len(valid_urls)}")

URLs validas encontradas: 62

In [5]:
# Lista fija para pruebas puntuales (comentar/descomentar segun necesidad)
italika_urls = [
    "https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p",
    "https://www.italika.mx/motoneta-italika-vitalia-150-beige-con-gps-34006773/p",
    "https://www.italika.mx/motocicleta-italika-dm300-dorado-con-gps-34006890/p",
    "https://www.italika.mx/motocicleta-deportiva-italika-vort-x-250-roja-con-negro-34005120/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-ts-roja-con-negro-34005164/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p",
    "https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p",
    "https://www.italika.mx/cuatrimoto-italika-atv-190-gris-34006332/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-at135x-verde-34006711/p",
    "https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-at125-grafito-34006712/p",
    "https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p",
    "https://www.italika.mx/motocicleta-italika-150z-negra-con-azul-con-gps-34007056/p",
    "https://www.italika.mx/motocicleta-chopper-italika-tc-250-gris-34006691/p",
    "https://www.italika.mx/motoneta-italika-bit-150-blanca-con-negro-34006931/p",
    "https://www.italika.mx/motocicleta-doble-proposito-italika-dm200-con-gps-azul-34006255-1300703478/p",
    "https://www.italika.mx/cuatrimoto-italika-atv300-azul-34006717/p",
    "https://www.italika.mx/motoneta-italika-d125-azul-con-negro-34006289/p",
    "https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p",
    "https://www.italika.mx/motoneta-italika-ws150-sport-marino-34006551/p",
    "https://www.italika.mx/motocicleta-italika-firebird-300-negra-con-gps-34007122/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-roja-34006714/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p",
    "https://www.italika.mx/motocicleta-doble-proposito-italika-dm150-con-gps-blanca-34006888/p",
    "https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-at110-rt-azul-34006720/p",
    "https://www.italika.mx/motocicleta-deportiva-italika-rt-250-con-gps-roja-34007114/p",
    "https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p",
    "https://www.italika.mx/motocicleta-italika-200z-azul-con-gps-34006885/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p",
    "https://www.italika.mx/motocicleta-italika-250z-carbono-negra-con-gps-34007058/p",
    "https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-gts-gris-con-gps-34007052/p",
    "https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p",
    "https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300r-azul-con-gris-34006484/p",
    "https://www.italika.mx/motoneta-italika-modena-175-con-gps-azul-34006716/p",
    "https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-at130-rt-blanca-34006713/p",
    "https://www.italika.mx/motoneta-italika-ds150-negra-34006307/p",
    "https://www.italika.mx/motocicleta-italika-ft150-gts-gris-con-amarillo-con-gps-34007053/p",
    "https://www.italika.mx/motocicleta-de-trabajo-italika-ft250-gts-con-gps-azul-con-negro-34006392/p",
    "https://www.italika.mx/motocicleta-urbana-italika-280z-con-gps-gris-34006887/p",
    "https://www.italika.mx/motocicleta-urbana-italika-125z-gris-con-gps-34006883/p",
]

## 5. Ejecutar price tracking

In [6]:
rows = run_price_tracking(
    urls=italika_urls,
    brand_name=BRAND_NAME,
)

## 6. Limpiar y mapear modelos

In [7]:
df_scraped = pd.DataFrame(rows)
df_scraped["year_scraped"] = YEAR_SCRAPED

df_scraped["model_name_clean"] = df_scraped["model_name"].apply(clean_model_name)

mapeo = load_mapping_file(COUNTRY, BRAND_NAME)
df_scraped["model_mapped"] = df_scraped["model_name_clean"].apply(lambda x: map_model_name(x, mapeo))
df_scraped["model_mapped"] = df_scraped["model_mapped"].str.lower()

df_scraped

Archivo de mapeo cargado correctamente: c:\Users\JTRUJILLO\Desktop\utiles\Proyectos\tracking_prices_changes\notebooks\test\..\..\src/data/json/replace_name/MX/italika_mapeo_nombres.json

,brand_name,model_name,url,price,price_type,currency,captured_at,change_status,previous_scrape_at,visibility,year_scraped,model_name_clean,model_mapped
0,Italika,motocicleta chopper italika rc200 gris,https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p,"27,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:05.848+00:00,visible,2026,rc200,rc200
1,Italika,motoneta italika vitalia 150 beige con gps,https://www.italika.mx/motoneta-italika-vitalia-150-beige-con-gps-34006773/p,"31,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:05.51+00:00,visible,2026,vitalia 150 gps,vitalia 150 gps
2,Italika,motocicleta italika dm300 dorado con gps,https://www.italika.mx/motocicleta-italika-dm300-dorado-con-gps-34006890/p,"42,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:06.181+00:00,visible,2026,dm300 gps,dm 300 gps
3,Italika,motocicleta deportiva italika vort x 250 roja con negro,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-250-roja-con-negro-34005120/p,"49,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,changed,2026-03-26T20:26:06.119+00:00,visible,2026,vort x 250,vort x 250
4,Italika,motocicleta de trabajo italika ft125 ts roja con negro,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-ts-roja-con-negro-34005164/p,"18,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:05.777+00:00,visible,2026,ft125 ts,ft 125 ts
5,Italika,motocicleta de trabajo italika ft150 ts negro con verde,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p,"21,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:15.556+00:00,visible,2026,ft150 ts,ft 150 ts
6,Italika,motoneta italika d150 blanco con azul,https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p,"22,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:16.38+00:00,visible,2026,d150,d150
7,Italika,cuatrimoto italika atv 190 gris,https://www.italika.mx/cuatrimoto-italika-atv-190-gris-34006332/p,"49,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:16.683+00:00,visible,2026,atv 190,atv 190
8,Italika,motocicleta de trabajo italika at135x verde,https://www.italika.mx/motocicleta-de-trabajo-italika-at135x-verde-34006711/p,"24,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:15.546+00:00,visible,2026,at135x,at135x
9,Italika,motocicleta urbana italika 280z gris,https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p,"41,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:15.724+00:00,visible,2026,280z,280z
10,Italika,motocicleta de trabajo italika at125 grafito,https://www.italika.mx/motocicleta-de-trabajo-italika-at125-grafito-34006712/p,"19,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:24.801+00:00,visible,2026,at125,at125
11,Italika,cuatrimoto italika atv200 naranja,https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p,"54,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:25.343+00:00,visible,2026,atv200,atv 200
12,Italika,motocicleta italika 150z negra con azul con gps,https://www.italika.mx/motocicleta-italika-150z-negra-con-azul-con-gps-34007056/p,"32,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,changed,2026-03-26T20:26:25.321+00:00,visible,2026,150z gps,150z gps
13,Italika,motocicleta chopper italika tc 250 gris,https://www.italika.mx/motocicleta-chopper-italika-tc-250-gris-34006691/p,"39,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:25.922+00:00,visible,2026,tc 250,tc 250
14,Italika,motoneta italika bit 150 blanca con negro,https://www.italika.mx/motoneta-italika-bit-150-blanca-con-negro-34006931/p,"28,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:25.702+00:00,visible,2026,bit 150,bit 150
15,Italika,motocicleta doble proposito italika dm200 con gps azul,https://www.italika.mx/motocicleta-doble-proposito-italika-dm200-con-gps-azul-34006255-1300703478/p,"30,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:35.098+00:00,visible,2026,dm200 gps,dm 200 gps
16,Italika,cuatrimoto italika atv300 azul,https://www.italika.mx/cuatrimoto-italika-atv300-azul-34006717/p,"84,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:35.786+00:00,visible,2026,atv300,atv 300
17,Italika,motoneta italika d125 azul con negro,https://www.italika.mx/motoneta-italika-d125-azul-con-negro-34006289/p,"18,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,changed,2026-03-26T20:26:34.84+00:00,visible,2026,d125,d125
18,Italika,motoneta italika ws175 sport grafito,https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p,"26,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:35.588+00:00,visible,2026,ws175 sport,ws 175 sport grafito
19,Italika,motoneta italika ws150 sport marino,https://www.italika.mx/motoneta-italika-ws150-sport-marino-34006551/p,"24,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:35.463+00:00,visible,2026,ws150 sport marino,ws 150 sport marino
20,Italika,motocicleta italika firebird 300 negra con gps,https://www.italika.mx/motocicleta-italika-firebird-300-negra-con-gps-34007122/p,"42,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:44.23+00:00,visible,2026,firebird 300 gps,firebird 300 gps
21,Italika,motocicleta de trabajo italika ft150 roja,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-roja-34006714/p,"19,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:43.36+00:00,visible,2026,ft150,ft 150
22,Italika,motocicleta de trabajo italika ft200 negra,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p,"25,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:45.017+00:00,visible,2026,ft200,ft 200
23,Italika,motocicleta doble proposito italika dm150 con gps blanca,https://www.italika.mx/motocicleta-doble-proposito-italika-dm150-con-gps-blanca-34006888/p,"27,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:45.216+00:00,visible,2026,dm150 gps,dm 150 gps
24,Italika,motoneta italika d150 lt negra,https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p,"19,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:46.298+00:00,visible,2026,d150 lt,d150 lt
25,Italika,motocicleta de trabajo italika at110 rt azul,https://www.italika.mx/motocicleta-de-trabajo-italika-at110-rt-azul-34006720/p,"17,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:52.018+00:00,visible,2026,at110 rt,at 110 rt
26,Italika,motocicleta deportiva italika rt 250 con gps roja,https://www.italika.mx/motocicleta-deportiva-italika-rt-250-con-gps-roja-34007114/p,"45,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:53.643+00:00,visible,2026,rt 250 gps,rt250 gps
27,Italika,motocicleta chopper italika tc 300 negra,https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p,"46,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:54.809+00:00,visible,2026,tc 300,tc 300
28,Italika,motocicleta italika 200z azul con gps,https://www.italika.mx/motocicleta-italika-200z-azul-con-gps-34006885/p,,contado,MXN,2026-03-31T20:28:05.167446+00:00,changed,2026-03-26T20:26:54.576+00:00,visible,2026,200z gps,200z gps
29,Italika,motocicleta de trabajo italika ft125 negra,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p,"17,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:55.776+00:00,visible,2026,ft125,ft 125
30,Italika,motocicleta italika 250z carbono negra con gps,https://www.italika.mx/motocicleta-italika-250z-carbono-negra-con-gps-34007058/p,"42,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:01.703+00:00,visible,2026,250z gps,250z gps
31,Italika,motocicleta cafe racer italika sptfire 250 plata,https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p,"25,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:03.137+00:00,visible,2026,sptfire 250,sptfire 250
32,Italika,motocicleta de trabajo italika ft200 gts gris con gps,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-gts-gris-con-gps-34007052/p,"29,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:03.739+00:00,visible,2026,ft200 gts gps,ft200 gts gps
33,Italika,motocicleta deportiva italika vort x 300 roja con negro,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p,"57,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:04.469+00:00,visible,2026,vort x 300,vort x 300
34,Italika,motocicleta deportiva italika vort x 300r azul con gris,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300r-azul-con-gris-34006484/p,"64,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:05.327+00:00,visible,2026,vort x 300r,vort x 300 racing
35,Italika,motoneta italika modena 175 con gps azul,https://www.italika.mx/motoneta-italika-modena-175-con-gps-azul-34006716/p,"31,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:11.035+00:00,visible,2026,modena 175 gps,modena 175 gps
36,Italika,motocicleta chopper italika rc250 negra,https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p,"30,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:12.357+00:00,visible,2026,rc250,rc250
37,Italika,motocicleta de trabajo italika at130 rt blanca,https://www.italika.mx/motocicleta-de-trabajo-italika-at130-rt-blanca-34006713/p,"21,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:14.142+00:00,visible,2026,at130 rt,at130 rt
38,Italika,motoneta italika ds150 negra,https://www.italika.mx/motoneta-italika-ds150-negra-34006307/p,"24,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:13.736+00:00,visible,2026,ds150,ds 150
39,Italika,motocicleta italika ft150 gts gris con amarillo con gps,https://www.italika.mx/motocicleta-italika-ft150-gts-gris-con-amarillo-con-gps-34007053/p,"23,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:14.199+00:00,visible,2026,ft150 gts gps,ft 150 gts gps
40,Italika,motocicleta de trabajo italika ft250 gts con gps azul con negro,https://www.italika.mx/motocicleta-de-trabajo-italika-ft250-gts-con-gps-azul-con-negro-34006392/p,"35,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:23.039+00:00,visible,2026,ft250 gts gps,ft 250 gts gps
41,Italika,motocicleta urbana italika 280z con gps gris,https://www.italika.mx/motocicleta-urbana-italika-280z-con-gps-gris-34006887/p,"45,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:22.115+00:00,visible,2026,280z gps,280z gps
42,Italika,motocicleta urbana italika 125z gris con gps,https://www.italika.mx/motocicleta-urbana-italika-125z-gris-con-gps-34006883/p,"26,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:24.376+00:00,visible,2026,125z gps,125z gps

## 7. Merge con inventario (inspeccion)

In [8]:
df_merged = pd.merge(
    df_scraped,
    df_inventory.assign(model_lower=df_inventory["model"].str.lower()),
    left_on="model_mapped",
    right_on="model_lower",
    how="left",
    indicator=True,
)
df_merged

,brand_name,model_name,url,price,price_type,currency,captured_at,change_status,previous_scrape_at,visibility,year_scraped,model_name_clean,model_mapped,date,code,brand,model,year,status,price_base,discount_amount,price_net,model_lower,_merge
0,Italika,motocicleta chopper italika rc200 gris,https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p,"27,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:05.848+00:00,visible,2026,rc200,rc200,30/03/2026,MX1314-italika-rc200,Italika,RC200,2025.0,available,27999.0,0.0,27999.0,rc200,both
1,Italika,motocicleta chopper italika rc200 gris,https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p,"27,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:05.848+00:00,visible,2026,rc200,rc200,30/03/2026,MX1314-italika-rc200,Italika,RC200,2026.0,no_stock,28999.0,0.0,28999.0,rc200,both
2,Italika,motoneta italika vitalia 150 beige con gps,https://www.italika.mx/motoneta-italika-vitalia-150-beige-con-gps-34006773/p,"31,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:05.51+00:00,visible,2026,vitalia 150 gps,vitalia 150 gps,30/03/2026,MX3412-italika-vitalia-150-gps,Italika,Vitalia 150 GPS,2026.0,available,32999.0,0.0,32999.0,vitalia 150 gps,both
3,Italika,motocicleta italika dm300 dorado con gps,https://www.italika.mx/motocicleta-italika-dm300-dorado-con-gps-34006890/p,"42,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:06.181+00:00,visible,2026,dm300 gps,dm 300 gps,30/03/2026,MX3401-italika-dm-300-gps,Italika,DM 300 GPS,2026.0,available,43999.0,0.0,43999.0,dm 300 gps,both
4,Italika,motocicleta deportiva italika vort x 250 roja con negro,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-250-roja-con-negro-34005120/p,"49,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,changed,2026-03-26T20:26:06.119+00:00,visible,2026,vort x 250,vort x 250,30/03/2026,MX2802-italika-vort-x-250,Italika,Vort X 250,2026.0,no_stock,50999.0,0.0,50999.0,vort x 250,both
5,Italika,motocicleta de trabajo italika ft125 ts roja con negro,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-ts-roja-con-negro-34005164/p,"18,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:05.777+00:00,visible,2026,ft125 ts,ft 125 ts,30/03/2026,MX1309-italika-ft-125-ts,Italika,FT 125 TS,2026.0,available,19999.0,0.0,19999.0,ft 125 ts,both
6,Italika,motocicleta de trabajo italika ft150 ts negro con verde,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p,"21,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:15.556+00:00,visible,2026,ft150 ts,ft 150 ts,30/03/2026,MX1311-italika-ft-150-ts,Italika,FT 150 TS,2025.0,available,19999.0,0.0,19999.0,ft 150 ts,both
7,Italika,motocicleta de trabajo italika ft150 ts negro con verde,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p,"21,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:15.556+00:00,visible,2026,ft150 ts,ft 150 ts,30/03/2026,MX1311-italika-ft-150-ts,Italika,FT 150 TS,2026.0,no_stock,22999.0,0.0,22999.0,ft 150 ts,both
8,Italika,motoneta italika d150 blanco con azul,https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p,"22,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:16.38+00:00,visible,2026,d150,d150,30/03/2026,MX1304-italika-d150,Italika,D150,2026.0,no_stock,23999.0,0.0,23999.0,d150,both
9,Italika,motoneta italika d150 blanco con azul,https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p,"22,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:16.38+00:00,visible,2026,d150,d150,30/03/2026,MX1304-italika-d150,Italika,D150,2025.0,available,19999.0,0.0,19999.0,d150,both
10,Italika,cuatrimoto italika atv 190 gris,https://www.italika.mx/cuatrimoto-italika-atv-190-gris-34006332/p,"49,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:16.683+00:00,visible,2026,atv 190,atv 190,30/03/2026,MX2656-italika-atv190,Italika,ATV 190,2026.0,available,50999.0,0.0,50999.0,atv 190,both
11,Italika,motocicleta de trabajo italika at135x verde,https://www.italika.mx/motocicleta-de-trabajo-italika-at135x-verde-34006711/p,"24,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:15.546+00:00,visible,2026,at135x,at135x,30/03/2026,MX3200-italika-at135x,Italika,AT135X,2026.0,available,25999.0,0.0,25999.0,at135x,both
12,Italika,motocicleta urbana italika 280z gris,https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p,"41,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:15.724+00:00,visible,2026,280z,280z,30/03/2026,MX2507-italika-280z,Italika,280Z,2025.0,available,42999.0,0.0,42999.0,280z,both
13,Italika,motocicleta urbana italika 280z gris,https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p,"41,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:15.724+00:00,visible,2026,280z,280z,30/03/2026,MX2507-italika-280z,Italika,280Z,2026.0,no_stock,42999.0,0.0,42999.0,280z,both
14,Italika,motocicleta de trabajo italika at125 grafito,https://www.italika.mx/motocicleta-de-trabajo-italika-at125-grafito-34006712/p,"19,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:24.801+00:00,visible,2026,at125,at125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
15,Italika,cuatrimoto italika atv200 naranja,https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p,"54,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:25.343+00:00,visible,2026,atv200,atv 200,30/03/2026,MX2771-italika-atv-200,Italika,ATV 200,2025.0,available,55999.0,0.0,55999.0,atv 200,both
16,Italika,cuatrimoto italika atv200 naranja,https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p,"54,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:25.343+00:00,visible,2026,atv200,atv 200,30/03/2026,MX2771-italika-atv-200,Italika,ATV 200,2026.0,no_stock,55999.0,0.0,55999.0,atv 200,both
17,Italika,motocicleta italika 150z negra con azul con gps,https://www.italika.mx/motocicleta-italika-150z-negra-con-azul-con-gps-34007056/p,"32,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,changed,2026-03-26T20:26:25.321+00:00,visible,2026,150z gps,150z gps,30/03/2026,MX3396-italika-150z-gps,Italika,150Z GPS,2026.0,available,33999.0,0.0,33999.0,150z gps,both
18,Italika,motocicleta chopper italika tc 250 gris,https://www.italika.mx/motocicleta-chopper-italika-tc-250-gris-34006691/p,"39,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:25.922+00:00,visible,2026,tc 250,tc 250,30/03/2026,MX2653-italika-tc-250,Italika,TC 250,2026.0,available,40999.0,0.0,40999.0,tc 250,both
19,Italika,motoneta italika bit 150 blanca con negro,https://www.italika.mx/motoneta-italika-bit-150-blanca-con-negro-34006931/p,"28,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:25.702+00:00,visible,2026,bit 150,bit 150,30/03/2026,MX2781-italika-bit-150,Italika,BIT 150,2026.0,available,29999.0,0.0,29999.0,bit 150,both
20,Italika,motocicleta doble proposito italika dm200 con gps azul,https://www.italika.mx/motocicleta-doble-proposito-italika-dm200-con-gps-azul-34006255-1300703478/p,"30,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:35.098+00:00,visible,2026,dm200 gps,dm 200 gps,30/03/2026,MX3402-italika-dm-200-gps,Italika,DM 200 GPS,2026.0,available,31999.0,0.0,31999.0,dm 200 gps,both
21,Italika,cuatrimoto italika atv300 azul,https://www.italika.mx/cuatrimoto-italika-atv300-azul-34006717/p,"84,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:35.786+00:00,visible,2026,atv300,atv 300,30/03/2026,MX3154-italika-atv-300,Italika,ATV 300,2026.0,no_stock,85999.0,0.0,85999.0,atv 300,both
22,Italika,motoneta italika d125 azul con negro,https://www.italika.mx/motoneta-italika-d125-azul-con-negro-34006289/p,"18,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,changed,2026-03-26T20:26:34.84+00:00,visible,2026,d125,d125,30/03/2026,MX1303-italika-d125,Italika,D125,2026.0,available,19999.0,0.0,19999.0,d125,both
23,Italika,motoneta italika ws175 sport grafito,https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p,"26,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:35.588+00:00,visible,2026,ws175 sport,ws 175 sport grafito,30/03/2026,MX2987-italika-ws-175-sport-grafito,Italika,WS 175 Sport Grafito,2025.0,available,28999.0,0.0,28999.0,ws 175 sport grafito,both
24,Italika,motoneta italika ws175 sport grafito,https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p,"26,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:35.588+00:00,visible,2026,ws175 sport,ws 175 sport grafito,30/03/2026,MX2987-italika-ws-175-sport-grafito,Italika,WS 175 Sport Grafito,2026.0,no_stock,27999.0,0.0,27999.0,ws 175 sport grafito,both
25,Italika,motoneta italika ws150 sport marino,https://www.italika.mx/motoneta-italika-ws150-sport-marino-34006551/p,"24,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:35.463+00:00,visible,2026,ws150 sport marino,ws 150 sport marino,30/03/2026,MX2969-italika-ws-150-sport-marino,Italika,WS 150 Sport Marino,2026.0,available,25999.0,0.0,25999.0,ws 150 sport marino,both
26,Italika,motocicleta italika firebird 300 negra con gps,https://www.italika.mx/motocicleta-italika-firebird-300-negra-con-gps-34007122/p,"42,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:44.23+00:00,visible,2026,firebird 300 gps,firebird 300 gps,30/03/2026,MX3454-italika-firebird-300-gps,Italika,Firebird 300 GPS,2026.0,no_stock,43999.0,0.0,43999.0,firebird 300 gps,both
27,Italika,motocicleta de trabajo italika ft150 roja,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-roja-34006714/p,"19,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:43.36+00:00,visible,2026,ft150,ft 150,30/03/2026,MX1277-italika-ft-150,Italika,FT 150,2026.0,available,20999.0,0.0,20999.0,ft 150,both
28,Italika,motocicleta de trabajo italika ft200 negra,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p,"25,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:45.017+00:00,visible,2026,ft200,ft 200,30/03/2026,MX2538-italika-ft200,Italika,FT 200,2025.0,available,24999.0,0.0,24999.0,ft 200,both
29,Italika,motocicleta de trabajo italika ft200 negra,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p,"25,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:45.017+00:00,visible,2026,ft200,ft 200,30/03/2026,MX2538-italika-ft200,Italika,FT 200,2026.0,available,26999.0,0.0,26999.0,ft 200,both
30,Italika,motocicleta doble proposito italika dm150 con gps blanca,https://www.italika.mx/motocicleta-doble-proposito-italika-dm150-con-gps-blanca-34006888/p,"27,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:45.216+00:00,visible,2026,dm150 gps,dm 150 gps,30/03/2026,MX3399-italika-dm-150-gps,Italika,DM 150 GPS,2026.0,available,28999.0,0.0,28999.0,dm 150 gps,both
31,Italika,motoneta italika d150 lt negra,https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p,"19,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:46.298+00:00,visible,2026,d150 lt,d150 lt,30/03/2026,MX2510-italika-dt-150,Italika,D150 LT,2026.0,no_stock,20999.0,0.0,20999.0,d150 lt,both
32,Italika,motoneta italika d150 lt negra,https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p,"19,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:46.298+00:00,visible,2026,d150 lt,d150 lt,30/03/2026,MX2510-italika-dt-150,Italika,D150 LT,2025.0,available,18999.0,0.0,18999.0,d150 lt,both
33,Italika,motocicleta de trabajo italika at110 rt azul,https://www.italika.mx/motocicleta-de-trabajo-italika-at110-rt-azul-34006720/p,"17,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:52.018+00:00,visible,2026,at110 rt,at 110 rt,30/03/2026,MX2769-italika-at-110-rt,Italika,AT 110 RT,2026.0,no_stock,18999.0,0.0,18999.0,at 110 rt,both
34,Italika,motocicleta deportiva italika rt 250 con gps roja,https://www.italika.mx/motocicleta-deportiva-italika-rt-250-con-gps-roja-34007114/p,"45,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:53.643+00:00,visible,2026,rt 250 gps,rt250 gps,30/03/2026,MX3411-italika-rt250-gps,Italika,RT250 GPS,2026.0,available,46999.0,0.0,46999.0,rt250 gps,both
35,Italika,motocicleta chopper italika tc 300 negra,https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p,"46,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:54.809+00:00,visible,2026,tc 300,tc 300,30/03/2026,MX2589-italika-tc-300,Italika,TC 300,2025.0,available,47999.0,0.0,47999.0,tc 300,both
36,Italika,motocicleta chopper italika tc 300 negra,https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p,"46,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:54.809+00:00,visible,2026,tc 300,tc 300,30/03/2026,MX2589-italika-tc-300,Italika,TC 300,2026.0,available,47999.0,0.0,47999.0,tc 300,both
37,Italika,motocicleta italika 200z azul con gps,https://www.italika.mx/motocicleta-italika-200z-azul-con-gps-34006885/p,,contado,MXN,2026-03-31T20:28:05.167446+00:00,changed,2026-03-26T20:26:54.576+00:00,visible,2026,200z gps,200z gps,30/03/2026,MX3397-italika-200z-gps,Italika,200Z GPS,2026.0,available,38999.0,0.0,38999.0,200z gps,both
38,Italika,motocicleta de trabajo italika ft125 negra,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p,"17,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:55.776+00:00,visible,2026,ft125,ft 125,30/03/2026,MX1308-italika-ft-125,Italika,FT 125,2025.0,available,18999.0,0.0,18999.0,ft 125,both
39,Italika,motocicleta de trabajo italika ft125 negra,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p,"17,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:26:55.776+00:00,visible,2026,ft125,ft 125,30/03/2026,MX1308-italika-ft-125,Italika,FT 125,2026.0,available,18999.0,0.0,18999.0,ft 125,both
40,Italika,motocicleta italika 250z carbono negra con gps,https://www.italika.mx/motocicleta-italika-250z-carbono-negra-con-gps-34007058/p,"42,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:01.703+00:00,visible,2026,250z gps,250z gps,30/03/2026,MX3398-italika-250z-gps,Italika,250Z GPS,2026.0,available,43999.0,0.0,43999.0,250z gps,both
41,Italika,motocicleta cafe racer italika sptfire 250 plata,https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p,"25,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:03.137+00:00,visible,2026,sptfire 250,sptfire 250,30/03/2026,MX2255-italika-sptfire-250,Italika,Sptfire 250,2026.0,available,26999.0,0.0,26999.0,sptfire 250,both
42,Italika,motocicleta cafe racer italika sptfire 250 plata,https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p,"25,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:03.137+00:00,visible,2026,sptfire 250,sptfire 250,30/03/2026,MX2255-italika-sptfire-250,Italika,Sptfire 250,2025.0,available,26999.0,0.0,26999.0,sptfire 250,both
43,Italika,motocicleta de trabajo italika ft200 gts gris con gps,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-gts-gris-con-gps-34007052/p,"29,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:03.739+00:00,visible,2026,ft200 gts gps,ft200 gts gps,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
44,Italika,motocicleta deportiva italika vort x 300 roja con negro,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p,"57,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:04.469+00:00,visible,2026,vort x 300,vort x 300,30/03/2026,MX2803-italika-vort-x-300,Italika,Vort X 300,2026.0,available,58999.0,0.0,58999.0,vort x 300,both
45,Italika,motocicleta deportiva italika vort x 300 roja con negro,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p,"57,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:04.469+00:00,visible,2026,vort x 300,vort x 300,30/03/2026,MX2803-italika-vort-x-300,Italika,Vort X 300,2025.0,available,58999.0,0.0,58999.0,vort x 300,both
46,Italika,motocicleta deportiva italika vort x 300r azul con gris,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300r-azul-con-gris-34006484/p,"64,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:05.327+00:00,visible,2026,vort x 300r,vort x 300 racing,30/03/2026,MX2827-italika-vort-x300-r-racing,Italika,Vort X 300 Racing,2026.0,available,65999.0,0.0,65999.0,vort x 300 racing,both
47,Italika,motoneta italika modena 175 con gps azul,https://www.italika.mx/motoneta-italika-modena-175-con-gps-azul-34006716/p,"31,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:11.035+00:00,visible,2026,modena 175 gps,modena 175 gps,30/03/2026,MX3410-italika-modena-175-gps,Italika,Modena 175 GPS,2026.0,available,32999.0,0.0,32999.0,modena 175 gps,both
48,Italika,motocicleta chopper italika rc250 negra,https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p,"30,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:12.357+00:00,visible,2026,rc250,rc250,30/03/2026,MX1409-italika-rc250-2023,Italika,RC250,2026.0,no_stock,31999.0,0.0,31999.0,rc250,both
49,Italika,motocicleta chopper italika rc250 negra,https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p,"30,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:12.357+00:00,visible,2026,rc250,rc250,30/03/2026,MX1409-italika-rc250-2023,Italika,RC250,2025.0,available,35999.0,0.0,35999.0,rc250,both
50,Italika,motocicleta de trabajo italika at130 rt blanca,https://www.italika.mx/motocicleta-de-trabajo-italika-at130-rt-blanca-34006713/p,"21,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:14.142+00:00,visible,2026,at130 rt,at130 rt,30/03/2026,MX3140-italika-at130-rt,Italika,AT130 RT,2026.0,available,22999.0,0.0,22999.0,at130 rt,both
51,Italika,motoneta italika ds150 negra,https://www.italika.mx/motoneta-italika-ds150-negra-34006307/p,"24,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:13.736+00:00,visible,2026,ds150,ds 150,30/03/2026,MX1338-italika-ds-150-g,Italika,DS 150,2026.0,no_stock,25999.0,0.0,25999.0,ds 150,both
52,Italika,motocicleta italika ft150 gts gris con amarillo con gps,https://www.italika.mx/motocicleta-italika-ft150-gts-gris-con-amarillo-con-gps-34007053/p,"23,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:14.199+00:00,visible,2026,ft150 gts gps,ft 150 gts gps,30/03/2026,MX3408-italika-ft-150-gts-gps,Italika,FT 150 GTS GPS,2026.0,available,24999.0,0.0,24999.0,ft 150 gts gps,both
53,Italika,motocicleta de trabajo italika ft250 gts con gps azul con negro,https://www.italika.mx/motocicleta-de-trabajo-italika-ft250-gts-con-gps-azul-con-negro-34006392/p,"35,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:23.039+00:00,visible,2026,ft250 gts gps,ft 250 gts gps,30/03/2026,MX3409-italika-ft-250-gts-gps,Italika,FT 250 GTS GPS,2026.0,available,36999.0,0.0,36999.0,ft 250 gts gps,both
54,Italika,motocicleta urbana italika 280z con gps gris,https://www.italika.mx/motocicleta-urbana-italika-280z-con-gps-gris-34006887/p,"45,999",contado,MXN,2026-03-31T20:28:05.167446+00:00,same,2026-03-26T20:27:22.115+00:00,visible,2026,280z gps,280z gps,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

## 8. Construir comparacion de precios

In [14]:
import pandas as pd

GALGO_FEE = 1000

_FINAL_COLUMNS = [
    "captured_at", "previous_scrape_at",
    "code", "brand", "model", "model_name", "year", "year_scraped", "status",
    "price_scraped", "price_scraped_with_galgo_fee", "price_base", "discount_amount",
    "price_net", "price_diff",
    "price_type", "currency", "change_status", "visibility",
    "url_scraped", "marketplace_url",
]


def build_price_comparison(
    df_scraped: pd.DataFrame,
    df_inventory: pd.DataFrame,
    country: str,
) -> pd.DataFrame:
    """Construye el DataFrame final de comparación de precios para Italika.

    Une el resultado del scraping con el inventario, aplica el fee de Galgo
    (+1000 MXN, exclusivo de Italika) y calcula la diferencia de precio.

    Args:
        df_scraped: DataFrame con columnas model_mapped y los campos del scrape.
        df_inventory: DataFrame del inventario filtrado por marca, con columna model_lower.
        country: Código de país (ej. 'MX'), usado para construir la URL de marketplace.

    Returns:
        DataFrame con columnas definidas en _FINAL_COLUMNS.
    """
    df = df_scraped.copy()
    df_inv = df_inventory.copy()
    df_inv["model_lower"] = df_inv["model"].str.lower()

    df_merged = pd.merge(
        df,
        df_inv,
        left_on="model_mapped",
        right_on="model_lower",
        how="left",
        indicator=True,
    )

    df_merged.rename(
        columns={"price": "price_scraped", "url": "url_scraped"},
        inplace=True,
    )

    df_merged["marketplace_url"] = df_merged["code"].apply(
        lambda code: f"https://www.galgo.com/{country.lower()}/motos/{code}"
    )

    price_clean = (
        df_merged["price_scraped"]
        .astype(str)
        .str.replace(",", "", regex=False)
    )
    df_merged["price_scraped_with_galgo_fee"] = (
        pd.to_numeric(price_clean, errors="coerce") + GALGO_FEE
    )

    df_merged["price_diff"] = (
        df_merged["price_scraped_with_galgo_fee"] - df_merged["price_net"]
    )

    existing_cols = [c for c in _FINAL_COLUMNS if c in df_merged.columns]
    return df_merged[existing_cols].copy()


df_final = build_price_comparison(df_scraped, df_inventory, COUNTRY)
df_final

,captured_at,previous_scrape_at,code,brand,model,model_name,year,year_scraped,status,price_scraped,price_scraped_with_galgo_fee,price_base,discount_amount,price_net,price_diff,price_type,currency,change_status,visibility,url_scraped,marketplace_url
0,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:05.848+00:00,MX1314-italika-rc200,Italika,RC200,motocicleta chopper italika rc200 gris,2025.0,2026,available,"27,999",28999.0,27999.0,0.0,27999.0,1000.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p,https://www.galgo.com/mx/motos/MX1314-italika-rc200
1,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:05.848+00:00,MX1314-italika-rc200,Italika,RC200,motocicleta chopper italika rc200 gris,2026.0,2026,no_stock,"27,999",28999.0,28999.0,0.0,28999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p,https://www.galgo.com/mx/motos/MX1314-italika-rc200
2,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:05.51+00:00,MX3412-italika-vitalia-150-gps,Italika,Vitalia 150 GPS,motoneta italika vitalia 150 beige con gps,2026.0,2026,available,"31,999",32999.0,32999.0,0.0,32999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-vitalia-150-beige-con-gps-34006773/p,https://www.galgo.com/mx/motos/MX3412-italika-vitalia-150-gps
3,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:06.181+00:00,MX3401-italika-dm-300-gps,Italika,DM 300 GPS,motocicleta italika dm300 dorado con gps,2026.0,2026,available,"42,999",43999.0,43999.0,0.0,43999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-italika-dm300-dorado-con-gps-34006890/p,https://www.galgo.com/mx/motos/MX3401-italika-dm-300-gps
4,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:06.119+00:00,MX2802-italika-vort-x-250,Italika,Vort X 250,motocicleta deportiva italika vort x 250 roja con negro,2026.0,2026,no_stock,"49,999",50999.0,50999.0,0.0,50999.0,0.0,contado,MXN,changed,visible,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-250-roja-con-negro-34005120/p,https://www.galgo.com/mx/motos/MX2802-italika-vort-x-250
5,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:05.777+00:00,MX1309-italika-ft-125-ts,Italika,FT 125 TS,motocicleta de trabajo italika ft125 ts roja con negro,2026.0,2026,available,"18,999",19999.0,19999.0,0.0,19999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-ts-roja-con-negro-34005164/p,https://www.galgo.com/mx/motos/MX1309-italika-ft-125-ts
6,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:15.556+00:00,MX1311-italika-ft-150-ts,Italika,FT 150 TS,motocicleta de trabajo italika ft150 ts negro con verde,2025.0,2026,available,"21,999",22999.0,19999.0,0.0,19999.0,3000.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p,https://www.galgo.com/mx/motos/MX1311-italika-ft-150-ts
7,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:15.556+00:00,MX1311-italika-ft-150-ts,Italika,FT 150 TS,motocicleta de trabajo italika ft150 ts negro con verde,2026.0,2026,no_stock,"21,999",22999.0,22999.0,0.0,22999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p,https://www.galgo.com/mx/motos/MX1311-italika-ft-150-ts
8,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:16.38+00:00,MX1304-italika-d150,Italika,D150,motoneta italika d150 blanco con azul,2026.0,2026,no_stock,"22,999",23999.0,23999.0,0.0,23999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p,https://www.galgo.com/mx/motos/MX1304-italika-d150
9,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:16.38+00:00,MX1304-italika-d150,Italika,D150,motoneta italika d150 blanco con azul,2025.0,2026,available,"22,999",23999.0,19999.0,0.0,19999.0,4000.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p,https://www.galgo.com/mx/motos/MX1304-italika-d150
10,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:16.683+00:00,MX2656-italika-atv190,Italika,ATV 190,cuatrimoto italika atv 190 gris,2026.0,2026,available,"49,999",50999.0,50999.0,0.0,50999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/cuatrimoto-italika-atv-190-gris-34006332/p,https://www.galgo.com/mx/motos/MX2656-italika-atv190
11,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:15.546+00:00,MX3200-italika-at135x,Italika,AT135X,motocicleta de trabajo italika at135x verde,2026.0,2026,available,"24,999",25999.0,25999.0,0.0,25999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-at135x-verde-34006711/p,https://www.galgo.com/mx/motos/MX3200-italika-at135x
12,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:15.724+00:00,MX2507-italika-280z,Italika,280Z,motocicleta urbana italika 280z gris,2025.0,2026,available,"41,999",42999.0,42999.0,0.0,42999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p,https://www.galgo.com/mx/motos/MX2507-italika-280z
13,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:15.724+00:00,MX2507-italika-280z,Italika,280Z,motocicleta urbana italika 280z gris,2026.0,2026,no_stock,"41,999",42999.0,42999.0,0.0,42999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p,https://www.galgo.com/mx/motos/MX2507-italika-280z
14,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:24.801+00:00,NaN,NaN,NaN,motocicleta de trabajo italika at125 grafito,NaN,2026,NaN,"19,999",20999.0,NaN,NaN,NaN,NaN,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-at125-grafito-34006712/p,https://www.galgo.com/mx/motos/nan
15,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:25.343+00:00,MX2771-italika-atv-200,Italika,ATV 200,cuatrimoto italika atv200 naranja,2025.0,2026,available,"54,999",55999.0,55999.0,0.0,55999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p,https://www.galgo.com/mx/motos/MX2771-italika-atv-200
16,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:25.343+00:00,MX2771-italika-atv-200,Italika,ATV 200,cuatrimoto italika atv200 naranja,2026.0,2026,no_stock,"54,999",55999.0,55999.0,0.0,55999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p,https://www.galgo.com/mx/motos/MX2771-italika-atv-200
17,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:25.321+00:00,MX3396-italika-150z-gps,Italika,150Z GPS,motocicleta italika 150z negra con azul con gps,2026.0,2026,available,"32,999",33999.0,33999.0,0.0,33999.0,0.0,contado,MXN,changed,visible,https://www.italika.mx/motocicleta-italika-150z-negra-con-azul-con-gps-34007056/p,https://www.galgo.com/mx/motos/MX3396-italika-150z-gps
18,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:25.922+00:00,MX2653-italika-tc-250,Italika,TC 250,motocicleta chopper italika tc 250 gris,2026.0,2026,available,"39,999",40999.0,40999.0,0.0,40999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-chopper-italika-tc-250-gris-34006691/p,https://www.galgo.com/mx/motos/MX2653-italika-tc-250
19,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:25.702+00:00,MX2781-italika-bit-150,Italika,BIT 150,motoneta italika bit 150 blanca con negro,2026.0,2026,available,"28,999",29999.0,29999.0,0.0,29999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-bit-150-blanca-con-negro-34006931/p,https://www.galgo.com/mx/motos/MX2781-italika-bit-150
20,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:35.098+00:00,MX3402-italika-dm-200-gps,Italika,DM 200 GPS,motocicleta doble proposito italika dm200 con gps azul,2026.0,2026,available,"30,999",31999.0,31999.0,0.0,31999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-doble-proposito-italika-dm200-con-gps-azul-34006255-1300703478/p,https://www.galgo.com/mx/motos/MX3402-italika-dm-200-gps
21,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:35.786+00:00,MX3154-italika-atv-300,Italika,ATV 300,cuatrimoto italika atv300 azul,2026.0,2026,no_stock,"84,999",85999.0,85999.0,0.0,85999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/cuatrimoto-italika-atv300-azul-34006717/p,https://www.galgo.com/mx/motos/MX3154-italika-atv-300
22,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:34.84+00:00,MX1303-italika-d125,Italika,D125,motoneta italika d125 azul con negro,2026.0,2026,available,"18,999",19999.0,19999.0,0.0,19999.0,0.0,contado,MXN,changed,visible,https://www.italika.mx/motoneta-italika-d125-azul-con-negro-34006289/p,https://www.galgo.com/mx/motos/MX1303-italika-d125
23,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:35.588+00:00,MX2987-italika-ws-175-sport-grafito,Italika,WS 175 Sport Grafito,motoneta italika ws175 sport grafito,2025.0,2026,available,"26,999",27999.0,28999.0,0.0,28999.0,-1000.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p,https://www.galgo.com/mx/motos/MX2987-italika-ws-175-sport-grafito
24,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:35.588+00:00,MX2987-italika-ws-175-sport-grafito,Italika,WS 175 Sport Grafito,motoneta italika ws175 sport grafito,2026.0,2026,no_stock,"26,999",27999.0,27999.0,0.0,27999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p,https://www.galgo.com/mx/motos/MX2987-italika-ws-175-sport-grafito
25,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:35.463+00:00,MX2969-italika-ws-150-sport-marino,Italika,WS 150 Sport Marino,motoneta italika ws150 sport marino,2026.0,2026,available,"24,999",25999.0,25999.0,0.0,25999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-ws150-sport-marino-34006551/p,https://www.galgo.com/mx/motos/MX2969-italika-ws-150-sport-marino
26,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:44.23+00:00,MX3454-italika-firebird-300-gps,Italika,Firebird 300 GPS,motocicleta italika firebird 300 negra con gps,2026.0,2026,no_stock,"42,999",43999.0,43999.0,0.0,43999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-italika-firebird-300-negra-con-gps-34007122/p,https://www.galgo.com/mx/motos/MX3454-italika-firebird-300-gps
27,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:43.36+00:00,MX1277-italika-ft-150,Italika,FT 150,motocicleta de trabajo italika ft150 roja,2026.0,2026,available,"19,999",20999.0,20999.0,0.0,20999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-roja-34006714/p,https://www.galgo.com/mx/motos/MX1277-italika-ft-150
28,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:45.017+00:00,MX2538-italika-ft200,Italika,FT 200,motocicleta de trabajo italika ft200 negra,2025.0,2026,available,"25,999",26999.0,24999.0,0.0,24999.0,2000.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p,https://www.galgo.com/mx/motos/MX2538-italika-ft200
29,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:45.017+00:00,MX2538-italika-ft200,Italika,FT 200,motocicleta de trabajo italika ft200 negra,2026.0,2026,available,"25,999",26999.0,26999.0,0.0,26999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p,https://www.galgo.com/mx/motos/MX2538-italika-ft200
30,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:45.216+00:00,MX3399-italika-dm-150-gps,Italika,DM 150 GPS,motocicleta doble proposito italika dm150 con gps blanca,2026.0,2026,available,"27,999",28999.0,28999.0,0.0,28999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-doble-proposito-italika-dm150-con-gps-blanca-34006888/p,https://www.galgo.com/mx/motos/MX3399-italika-dm-150-gps
31,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:46.298+00:00,MX2510-italika-dt-150,Italika,D150 LT,motoneta italika d150 lt negra,2026.0,2026,no_stock,"19,999",20999.0,20999.0,0.0,20999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p,https://www.galgo.com/mx/motos/MX2510-italika-dt-150
32,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:46.298+00:00,MX2510-italika-dt-150,Italika,D150 LT,motoneta italika d150 lt negra,2025.0,2026,available,"19,999",20999.0,18999.0,0.0,18999.0,2000.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p,https://www.galgo.com/mx/motos/MX2510-italika-dt-150
33,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:52.018+00:00,MX2769-italika-at-110-rt,Italika,AT 110 RT,motocicleta de trabajo italika at110 rt azul,2026.0,2026,no_stock,"17,999",18999.0,18999.0,0.0,18999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-at110-rt-azul-34006720/p,https://www.galgo.com/mx/motos/MX2769-italika-at-110-rt
34,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:53.643+00:00,MX3411-italika-rt250-gps,Italika,RT250 GPS,motocicleta deportiva italika rt 250 con gps roja,2026.0,2026,available,"45,999",46999.0,46999.0,0.0,46999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-deportiva-italika-rt-250-con-gps-roja-34007114/p,https://www.galgo.com/mx/motos/MX3411-italika-rt250-gps
35,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:54.809+00:00,MX2589-italika-tc-300,Italika,TC 300,motocicleta chopper italika tc 300 negra,2025.0,2026,available,"46,999",47999.0,47999.0,0.0,47999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p,https://www.galgo.com/mx/motos/MX2589-italika-tc-300
36,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:54.809+00:00,MX2589-italika-tc-300,Italika,TC 300,motocicleta chopper italika tc 300 negra,2026.0,2026,available,"46,999",47999.0,47999.0,0.0,47999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p,https://www.galgo.com/mx/motos/MX2589-italika-tc-300
37,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:54.576+00:00,MX3397-italika-200z-gps,Italika,200Z GPS,motocicleta italika 200z azul con gps,2026.0,2026,available,,NaN,38999.0,0.0,38999.0,NaN,contado,MXN,changed,visible,https://www.italika.mx/motocicleta-italika-200z-azul-con-gps-34006885/p,https://www.galgo.com/mx/motos/MX3397-italika-200z-gps
38,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:55.776+00:00,MX1308-italika-ft-125,Italika,FT 125,motocicleta de trabajo italika ft125 negra,2025.0,2026,available,"17,999",18999.0,18999.0,0.0,18999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p,https://www.galgo.com/mx/motos/MX1308-italika-ft-125
39,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:55.776+00:00,MX1308-italika-ft-125,Italika,FT 125,motocicleta de trabajo italika ft125 negra,2026.0,2026,available,"17,999",18999.0,18999.0,0.0,18999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p,https://www.galgo.com/mx/motos/MX1308-italika-ft-125
40,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:01.703+00:00,MX3398-italika-250z-gps,Italika,250Z GPS,motocicleta italika 250z carbono negra con gps,2026.0,2026,available,"42,999",43999.0,43999.0,0.0,43999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-italika-250z-carbono-negra-con-gps-34007058/p,https://www.galgo.com/mx/motos/MX3398-italika-250z-gps
41,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:03.137+00:00,MX2255-italika-sptfire-250,Italika,Sptfire 250,motocicleta cafe racer italika sptfire 250 plata,2026.0,2026,available,"25,999",26999.0,26999.0,0.0,26999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p,https://www.galgo.com/mx/motos/MX2255-italika-sptfire-250
42,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:03.137+00:00,MX2255-italika-sptfire-250,Italika,Sptfire 250,motocicleta cafe racer italika sptfire 250 plata,2025.0,2026,available,"25,999",26999.0,26999.0,0.0,26999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p,https://www.galgo.com/mx/motos/MX2255-italika-sptfire-250
43,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:03.739+00:00,NaN,NaN,NaN,motocicleta de trabajo italika ft200 gts gris con gps,NaN,2026,NaN,"29,999",30999.0,NaN,NaN,NaN,NaN,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-gts-gris-con-gps-34007052/p,https://www.galgo.com/mx/motos/nan
44,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:04.469+00:00,MX2803-italika-vort-x-300,Italika,Vort X 300,motocicleta deportiva italika vort x 300 roja con negro,2026.0,2026,available,"57,999",58999.0,58999.0,0.0,58999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p,https://www.galgo.com/mx/motos/MX2803-italika-vort-x-300
45,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:04.469+00:00,MX2803-italika-vort-x-300,Italika,Vort X 300,motocicleta deportiva italika vort x 300 roja con negro,2025.0,2026,available,"57,999",58999.0,58999.0,0.0,58999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p,https://www.galgo.com/mx/motos/MX2803-italika-vort-x-300
46,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:05.327+00:00,MX2827-italika-vort-x300-r-racing,Italika,Vort X 300 Racing,motocicleta deportiva italika vort x 300r azul con gris,2026.0,2026,available,"64,999",65999.0,65999.0,0.0,65999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300r-azul-con-gris-34006484/p,https://www.galgo.com/mx/motos/MX2827-italika-vort-x300-r-racing
47,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:11.035+00:00,MX3410-italika-modena-175-gps,Italika,Modena 175 GPS,motoneta italika modena 175 con gps azul,2026.0,2026,available,"31,999",32999.0,32999.0,0.0,32999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-modena-175-con-gps-azul-34006716/p,https://www.galgo.com/mx/motos/MX3410-italika-modena-175-gps
48,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:12.357+00:00,MX1409-italika-rc250-2023,Italika,RC250,motocicleta chopper italika rc250 negra,2026.0,2026,no_stock,"30,999",31999.0,31999.0,0.0,31999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p,https://www.galgo.com/mx/motos/MX1409-italika-rc250-2023
49,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:12.357+00:00,MX1409-italika-rc250-2023,Italika,RC250,motocicleta chopper italika rc250 negra,2025.0,2026,available,"30,999",31999.0,35999.0,0.0,35999.0,-4000.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p,https://www.galgo.com/mx/motos/MX1409-italika-rc250-2023
50,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:14.142+00:00,MX3140-italika-at130-rt,Italika,AT130 RT,motocicleta de trabajo italika at130 rt blanca,2026.0,2026,available,"21,999",22999.0,22999.0,0.0,22999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-at130-rt-blanca-34006713/p,https://www.galgo.com/mx/motos/MX3140-italika-at130-rt
51,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:13.736+00:00,MX1338-italika-ds-150-g,Italika,DS 150,motoneta italika ds150 negra,2026.0,2026,no_stock,"24,999",25999.0,25999.0,0.0,25999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motoneta-italika-ds150-negra-34006307/p,https://www.galgo.com/mx/motos/MX1338-italika-ds-150-g
52,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:14.199+00:00,MX3408-italika-ft-150-gts-gps,Italika,FT 150 GTS GPS,motocicleta italika ft150 gts gris con amarillo con gps,2026.0,2026,available,"23,999",24999.0,24999.0,0.0,24999.0,0.0,contado,MXN,same,visible,https://www.italika.mx/motocicleta-italika-ft150-gts-gris-con-amarillo-con-gps-34007053/p,https://www.galgo.com/mx/motos/MX3408-italika-ft-150-gts-gps

## 9. Inspeccion

In [15]:
# Modelos scrapeados sin match en inventario
sin_match = df_merged[df_merged["_merge"] == "left_only"][["model_name", "model_name_clean", "model_mapped"]].drop_duplicates()
print(f"Sin match en inventario: {len(sin_match)}")
sin_match

Sin match en inventario: 3

,model_name,model_name_clean,model_mapped
14,motocicleta de trabajo italika at125 grafito,at125,at125
43,motocicleta de trabajo italika ft200 gts gris con gps,ft200 gts gps,ft200 gts gps
54,motocicleta urbana italika 280z con gps gris,280z gps,280z gps

In [16]:
# Filas sin codigo de inventario
df_final[df_final["code"].isna()]

,captured_at,previous_scrape_at,code,brand,model,model_name,year,year_scraped,status,price_scraped,price_scraped_with_galgo_fee,price_base,discount_amount,price_net,price_diff,price_type,currency,change_status,visibility,url_scraped,marketplace_url
14,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:26:24.801+00:00,NaN,NaN,NaN,motocicleta de trabajo italika at125 grafito,NaN,2026,NaN,"19,999",20999.0,NaN,NaN,NaN,NaN,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-at125-grafito-34006712/p,https://www.galgo.com/mx/motos/nan
43,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:03.739+00:00,NaN,NaN,NaN,motocicleta de trabajo italika ft200 gts gris con gps,NaN,2026,NaN,"29,999",30999.0,NaN,NaN,NaN,NaN,contado,MXN,same,visible,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-gts-gris-con-gps-34007052/p,https://www.galgo.com/mx/motos/nan
54,2026-03-31T20:28:05.167446+00:00,2026-03-26T20:27:22.115+00:00,NaN,NaN,NaN,motocicleta urbana italika 280z con gps gris,NaN,2026,NaN,"45,999",46999.0,NaN,NaN,NaN,NaN,contado,MXN,same,visible,https://www.italika.mx/motocicleta-urbana-italika-280z-con-gps-gris-34006887/p,https://www.galgo.com/mx/motos/nan

## 10. Exportar

In [17]:
output_file = f"31032026-{BRAND_NAME}_precios.csv"
df_final.to_csv(output_file, index=False)
print(f"Archivo exportado: {output_file} — {len(df_final)} filas")

Archivo exportado: 31032026-Italika_precios.csv — 56 filas

---
## Anexo: correr sobre catalogo completo

In [18]:
# # Descomentar para correr sobre todas las URLs validas del catalogo
# rows_full = run_price_tracking(
#     urls=valid_urls,
#     brand_name=BRAND_NAME,
# )
# df_full = pd.DataFrame(rows_full)
# print(f"Modelos procesados: {len(df_full)}")
# print(df_full["change_status"].value_counts().to_dict())
# df_full.head()