Output: https://docs.google.com/spreadsheets/d/1UuwjLSfpOF-fYhOSv7Tw_iIJeqaAkItDZWURfo4cy1Q/edit?usp=sharing

## 1. Setup e imports

In [1]:
import re
import sys
import pandas as pd
from dotenv import load_dotenv

# Raiz del proyecto (ejecutar desde notebooks/)
sys.path.append("../")
load_dotenv("../.env")
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)

from src.config.settings import COUNTRY
from src.config.brand_configs import BRAND_FEES
from src.core.price_tracking.price_tracking import run_price_tracking
from src.utils.clean_model_name import clean_model_name
from src.utils.replace_model_name import map_model_name, load_mapping_file
from src.core.italika_pipeline import build_price_comparison
from src.sources.sheets.reader import GoogleSheetReader
from src.core.scraper.app import ScrapingUtils

gsheets = GoogleSheetReader()
scraper = ScrapingUtils()

In [2]:
# urls_scraped = scraper.get_all_urls_from_website("https://www.motosbajaj.com.mx/")

In [3]:
# urls = []
# for url in urls_scraped:
#     if "product-page" in url:
#         urls.append(url)

## 2. Configuracion

In [4]:
BRAND_NAME = "Italika"

In [5]:
import json
from pathlib import Path

# Carga URLs desde el JSON correspondiente a la marca seleccionada
json_path = Path("../src/data/json/brand_urls") / f"{BRAND_NAME.lower()}.json"

with open(json_path, "r", encoding="utf-8") as f:
    urls_to_scrape = json.load(f)["urls"]

print(f"{len(urls_to_scrape)} URLs cargadas para {BRAND_NAME}")

43 URLs cargadas para Italika

## Lectura de base de inventario

Lectura desde archivo local

In [6]:
# CSV_PATH = rf"C:\Users\JTRUJILLO\Desktop\utiles\Reportes\historical_data\src\data\prices\{COUNTRY}-prices.csv"
# df_inventory = pd.read_csv(CSV_PATH)

Lectura desde archivo en google sheets

In [7]:
google_sheet_info = {
    "sheet_name": '[MKP] Precios',
    "worksheet": f'price_data_mx',
}
df_inventory = gsheets.read_sheet(google_sheet_info)

In [8]:
df_inventory[df_inventory["model"] == "RC250"]

,date,code,brand,model,year,status,price_base,discount_amount,price_net
64,14/04/2026,MX1409-italika-rc250-2023,Italika,RC250,2023,discontinued,33999.0,0.0,33999.0
269,14/04/2026,MX1409-italika-rc250-2023,Italika,RC250,2026,no_stock,31999.0,0.0,31999.0
700,14/04/2026,MX1409-italika-rc250-2023,Italika,RC250,2025,available,31999.0,0.0,31999.0
1448,14/04/2026,MX1409-italika-rc250-2023,Italika,RC250,2024,discontinued,31999.0,0.0,31999.0

## 3. Cargar inventario

In [9]:
df_inventory = df_inventory[df_inventory["brand"] == BRAND_NAME]
df_inventory = df_inventory[df_inventory["status"].isin(["available", "no_stock"])] # Modelos disponibles en marketplace

## 4. Definir URLs a scrapear (input manual)

In [10]:
if not urls_to_scrape:
    raise ValueError("Debes cargar al menos una URL en 'urls_to_scrape'")

print(f"URLs recibidas para scraping: {len(urls_to_scrape)}")

URLs recibidas para scraping: 43

## 5. Ejecutar price tracking

In [11]:
rows = run_price_tracking(
    urls=urls_to_scrape,
    brand_name=BRAND_NAME,
)

In [12]:
df_scraped = pd.DataFrame(rows)
df_scraped

,brand_name,model_name,year_scraped,url,price,price_type,currency,captured_at,change_status,previous_scrape_at,visibility
0,Italika,motocicleta chopper italika rc200 gris,2026,https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p,"27,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
1,Italika,motoneta italika vitalia 150 beige con gps,2026,https://www.italika.mx/motoneta-italika-vitalia-150-beige-con-gps-34006773/p,"31,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
2,Italika,motocicleta italika dm300 dorado con gps,2026,https://www.italika.mx/motocicleta-italika-dm300-dorado-con-gps-34006890/p,"42,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
3,Italika,motocicleta deportiva italika vort x 250 roja con negro,2026,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-250-roja-con-negro-34005120/p,"49,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
4,Italika,motocicleta de trabajo italika ft125 ts roja con negro,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-ts-roja-con-negro-34005164/p,"18,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
5,Italika,motocicleta de trabajo italika ft150 ts negro con verde,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p,"20,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
6,Italika,motoneta italika d150 blanco con azul,2026,https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p,"22,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
7,Italika,cuatrimoto italika atv 190 gris,2026,https://www.italika.mx/cuatrimoto-italika-atv-190-gris-34006332/p,"49,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
8,Italika,motocicleta de trabajo italika at135x verde,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-at135x-verde-34006711/p,"24,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
9,Italika,motocicleta urbana italika 280z gris,2026,https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p,"41,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
10,Italika,motocicleta de trabajo italika at125 grafito,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-at125-grafito-34006712/p,"19,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
11,Italika,cuatrimoto italika atv200 naranja,2026,https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p,"54,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
12,Italika,motocicleta italika 150z negra con azul con gps,2026,https://www.italika.mx/motocicleta-italika-150z-negra-con-azul-con-gps-34007056/p,"32,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
13,Italika,motocicleta chopper italika tc 250 gris,2026,https://www.italika.mx/motocicleta-chopper-italika-tc-250-gris-34006691/p,"39,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
14,Italika,motoneta italika bit 150 blanca con negro,2026,https://www.italika.mx/motoneta-italika-bit-150-blanca-con-negro-34006931/p,"28,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
15,Italika,motocicleta doble proposito italika dm200 con gps azul,2026,https://www.italika.mx/motocicleta-doble-proposito-italika-dm200-con-gps-azul-34006255-1300703478/p,"30,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
16,Italika,cuatrimoto italika atv300 azul,2026,https://www.italika.mx/cuatrimoto-italika-atv300-azul-34006717/p,"84,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
17,Italika,motoneta italika d125 azul con negro,2026,https://www.italika.mx/motoneta-italika-d125-azul-con-negro-34006289/p,"18,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
18,Italika,motoneta italika ws175 sport grafito,2026,https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p,"26,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
19,Italika,motoneta italika ws150 sport marino,2026,https://www.italika.mx/motoneta-italika-ws150-sport-marino-34006551/p,"24,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
20,Italika,motocicleta italika firebird 300 negra con gps,2026,https://www.italika.mx/motocicleta-italika-firebird-300-negra-con-gps-34007122/p,"42,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
21,Italika,motocicleta de trabajo italika ft150 roja,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-roja-34006714/p,"19,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
22,Italika,motocicleta de trabajo italika ft200 negra,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p,"25,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
23,Italika,motocicleta doble proposito italika dm150 con gps blanca,2026,https://www.italika.mx/motocicleta-doble-proposito-italika-dm150-con-gps-blanca-34006888/p,"27,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
24,Italika,motoneta italika d150 lt negra,2026,https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p,"19,499",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
25,Italika,motocicleta de trabajo italika at110 rt azul,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-at110-rt-azul-34006720/p,"17,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
26,Italika,motocicleta deportiva italika rt 250 con gps roja,2026,https://www.italika.mx/motocicleta-deportiva-italika-rt-250-con-gps-roja-34007114/p,"45,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
27,Italika,motocicleta chopper italika tc 300 negra,2026,https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p,"46,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
28,Italika,motocicleta italika 200z azul con gps,2026,https://www.italika.mx/motocicleta-italika-200z-azul-con-gps-34006885/p,"37,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
29,Italika,motocicleta de trabajo italika ft125 negra,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p,"17,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
30,Italika,motocicleta italika 250z carbono negra con gps,2026,https://www.italika.mx/motocicleta-italika-250z-carbono-negra-con-gps-34007058/p,"42,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
31,Italika,motocicleta cafe racer italika sptfire 250 plata,2026,https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p,"25,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
32,Italika,motocicleta de trabajo italika ft200 gts gris con gps,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-gts-gris-con-gps-34007052/p,"29,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
33,Italika,motocicleta deportiva italika vort x 300 roja con negro,2026,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p,"57,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
34,Italika,motocicleta deportiva italika vort x 300r azul con gris,2026,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300r-azul-con-gris-34006484/p,"64,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
35,Italika,motoneta italika modena 175 con gps azul,2026,https://www.italika.mx/motoneta-italika-modena-175-con-gps-azul-34006716/p,"31,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
36,Italika,motocicleta chopper italika rc250 negra,2026,https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p,"30,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
37,Italika,motocicleta de trabajo italika at130 rt blanca,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-at130-rt-blanca-34006713/p,"21,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
38,Italika,motoneta italika ds150 negra,2026,https://www.italika.mx/motoneta-italika-ds150-negra-34006307/p,"24,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
39,Italika,motocicleta italika ft150 gts gris con amarillo con gps,2026,https://www.italika.mx/motocicleta-italika-ft150-gts-gris-con-amarillo-con-gps-34007053/p,"23,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
40,Italika,motocicleta de trabajo italika ft250 gts con gps azul con negro,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-ft250-gts-con-gps-azul-con-negro-34006392/p,"35,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
41,Italika,motocicleta urbana italika 280z con gps gris,2026,https://www.italika.mx/motocicleta-urbana-italika-280z-con-gps-gris-34006887/p,"45,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,
42,Italika,motocicleta urbana italika 125z gris con gps,2026,https://www.italika.mx/motocicleta-urbana-italika-125z-gris-con-gps-34006883/p,"26,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,

## 6. Limpiar y mapear modelos

In [13]:
df_scraped["year_scraped"] = pd.to_numeric(df_scraped.get("year_scraped"), errors="coerce").astype("Int64")

df_scraped["model_name_clean"] = df_scraped["model_name"].apply(
    lambda model_name: clean_model_name(model_name, brand_name=BRAND_NAME)
)

mapeo = load_mapping_file(COUNTRY, BRAND_NAME)
df_scraped["model_mapped"] = df_scraped["model_name_clean"].apply(lambda x: map_model_name(x, mapeo))
df_scraped["model_mapped"] = df_scraped["model_mapped"].str.lower()

Archivo de mapeo cargado correctamente: C:\Users\JTRUJILLO\Desktop\utiles\Proyectos\tracking_prices_changes\src/data/json/replace_name/MX/italika_mapeo_nombres.json

## 7. Merge con inventario (inspeccion)

In [14]:
# 1) Preparar inventario (marketplace)
inv_for_merge = df_inventory.copy()
inv_for_merge["model_lower"] = inv_for_merge["model"].str.lower()
inv_for_merge["year"] = pd.to_numeric(inv_for_merge["year"], errors="coerce")

# 2) Preparar scrapeado
scraped_for_merge = df_scraped.copy()
scraped_for_merge["year_scraped"] = pd.to_numeric(
    scraped_for_merge.get("year_scraped"),
    errors="coerce",
)

# 3) Merge por modelo + año
# Comentario en español: Outer conserva tanto marketplace sin match como scrapeado sin match.
df_merged = pd.merge(
    inv_for_merge,
    scraped_for_merge,
    left_on=["model_lower", "year"],
    right_on=["model_mapped", "year_scraped"],
    how="outer",
    indicator=True,
)

df_merged.head(2)

,date,code,brand,model,year,status,price_base,discount_amount,price_net,model_lower,brand_name,model_name,year_scraped,url,price,price_type,currency,captured_at,change_status,previous_scrape_at,visibility,model_name_clean,model_mapped,_merge
0,14/04/2026,MX3395-italika-125z-gps,Italika,125Z GPS,2026.0,available,27999.0,0.0,27999.0,125z gps,Italika,motocicleta urbana italika 125z gris con gps,2026,https://www.italika.mx/motocicleta-urbana-italika-125z-gris-con-gps-34006883/p,"26,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,,125z gps,125z gps,both
1,14/04/2026,MX3396-italika-150z-gps,Italika,150Z GPS,2026.0,available,33999.0,0.0,33999.0,150z gps,Italika,motocicleta italika 150z negra con azul con gps,2026,https://www.italika.mx/motocicleta-italika-150z-negra-con-azul-con-gps-34007056/p,"32,999",contado,MXN,2026-04-14T21:06:15.464715+00:00,,,,150z gps,150z gps,both

## 8. Construir comparacion de precios

In [15]:
df_final = build_price_comparison(
    df_scraped,
    df_inventory,
    COUNTRY,
    galgo_fee=BRAND_FEES.get(BRAND_NAME.lower(), 0),
)

In [16]:
df_final[df_final["url_scraped"].notna()]

,captured_at,previous_scrape_at,code,brand,model,model_name,year,year_scraped,status,price_scraped,price_scraped_with_galgo_fee,price_base,discount_amount,price_net,price_diff,price_type,currency,change_status,visibility,year_match_type,url_scraped,marketplace_url
0,2026-04-14T21:06:15.464715+00:00,,MX3454-italika-firebird-300-gps,Italika,Firebird 300 GPS,motocicleta italika firebird 300 negra con gps,2026,2026,no_stock,"42,999",43999.0,43999.0,0.0,43999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-italika-firebird-300-negra-con-gps-34007122/p,https://www.galgo.com/mx/motos/MX3454-italika-firebird-300-gps
1,2026-04-14T21:06:15.464715+00:00,,MX3140-italika-at130-rt,Italika,AT130 RT,motocicleta de trabajo italika at130 rt blanca,2026,2026,available,"21,999",22999.0,22999.0,0.0,22999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-de-trabajo-italika-at130-rt-blanca-34006713/p,https://www.galgo.com/mx/motos/MX3140-italika-at130-rt
2,2026-04-14T21:06:15.464715+00:00,,MX2969-italika-ws-150-sport-marino,Italika,WS 150 Sport Marino,motoneta italika ws150 sport marino,2026,2026,available,"24,999",25999.0,25999.0,0.0,25999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motoneta-italika-ws150-sport-marino-34006551/p,https://www.galgo.com/mx/motos/MX2969-italika-ws-150-sport-marino
3,2026-04-14T21:06:15.464715+00:00,,MX2653-italika-tc-250,Italika,TC 250,motocicleta chopper italika tc 250 gris,2026,2026,available,"39,999",40999.0,40999.0,0.0,40999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-chopper-italika-tc-250-gris-34006691/p,https://www.galgo.com/mx/motos/MX2653-italika-tc-250
4,2026-04-14T21:06:15.464715+00:00,,MX1409-italika-rc250-2023,Italika,RC250,motocicleta chopper italika rc250 negra,2026,2026,no_stock,"30,999",31999.0,31999.0,0.0,31999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p,https://www.galgo.com/mx/motos/MX1409-italika-rc250-2023
5,2026-04-14T21:06:15.464715+00:00,,MX2771-italika-atv-200,Italika,ATV 200,cuatrimoto italika atv200 naranja,2026,2026,no_stock,"54,999",55999.0,55999.0,0.0,55999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p,https://www.galgo.com/mx/motos/MX2771-italika-atv-200
6,2026-04-14T21:06:15.464715+00:00,,MX2827-italika-vort-x300-r-racing,Italika,Vort X 300 Racing,motocicleta deportiva italika vort x 300r azul con gris,2026,2026,available,"64,999",65999.0,65999.0,0.0,65999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300r-azul-con-gris-34006484/p,https://www.galgo.com/mx/motos/MX2827-italika-vort-x300-r-racing
7,2026-04-14T21:06:15.464715+00:00,,MX2769-italika-at-110-rt,Italika,AT 110 RT,motocicleta de trabajo italika at110 rt azul,2026,2026,no_stock,"17,999",18999.0,18999.0,0.0,18999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-de-trabajo-italika-at110-rt-azul-34006720/p,https://www.galgo.com/mx/motos/MX2769-italika-at-110-rt
8,2026-04-14T21:06:15.464715+00:00,,MX3396-italika-150z-gps,Italika,150Z GPS,motocicleta italika 150z negra con azul con gps,2026,2026,available,"32,999",33999.0,33999.0,0.0,33999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-italika-150z-negra-con-azul-con-gps-34007056/p,https://www.galgo.com/mx/motos/MX3396-italika-150z-gps
9,2026-04-14T21:06:15.464715+00:00,,MX2802-italika-vort-x-250,Italika,Vort X 250,motocicleta deportiva italika vort x 250 roja con negro,2026,2026,no_stock,"49,999",50999.0,50999.0,0.0,50999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-250-roja-con-negro-34005120/p,https://www.galgo.com/mx/motos/MX2802-italika-vort-x-250
10,2026-04-14T21:06:15.464715+00:00,,MX3200-italika-at135x,Italika,AT135X,motocicleta de trabajo italika at135x verde,2026,2026,available,"24,999",25999.0,25999.0,0.0,25999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-de-trabajo-italika-at135x-verde-34006711/p,https://www.galgo.com/mx/motos/MX3200-italika-at135x
11,2026-04-14T21:06:15.464715+00:00,,MX3154-italika-atv-300,Italika,ATV 300,cuatrimoto italika atv300 azul,2026,2026,no_stock,"84,999",85999.0,85999.0,0.0,85999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/cuatrimoto-italika-atv300-azul-34006717/p,https://www.galgo.com/mx/motos/MX3154-italika-atv-300
12,2026-04-14T21:06:15.464715+00:00,,MX3395-italika-125z-gps,Italika,125Z GPS,motocicleta urbana italika 125z gris con gps,2026,2026,available,"26,999",27999.0,27999.0,0.0,27999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-urbana-italika-125z-gris-con-gps-34006883/p,https://www.galgo.com/mx/motos/MX3395-italika-125z-gps
13,2026-04-14T21:06:15.464715+00:00,,MX3408-italika-ft-150-gts-gps,Italika,FT 150 GTS GPS,motocicleta italika ft150 gts gris con amarillo con gps,2026,2026,available,"23,999",24999.0,24999.0,0.0,24999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-italika-ft150-gts-gris-con-amarillo-con-gps-34007053/p,https://www.galgo.com/mx/motos/MX3408-italika-ft-150-gts-gps
14,2026-04-14T21:06:15.464715+00:00,,MX1277-italika-ft-150,Italika,FT 150,motocicleta de trabajo italika ft150 roja,2026,2026,available,"19,999",20999.0,20999.0,0.0,20999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-roja-34006714/p,https://www.galgo.com/mx/motos/MX1277-italika-ft-150
15,2026-04-14T21:06:15.464715+00:00,,MX3409-italika-ft-250-gts-gps,Italika,FT 250 GTS GPS,motocicleta de trabajo italika ft250 gts con gps azul con negro,2026,2026,available,"35,999",36999.0,36999.0,0.0,36999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-de-trabajo-italika-ft250-gts-con-gps-azul-con-negro-34006392/p,https://www.galgo.com/mx/motos/MX3409-italika-ft-250-gts-gps
16,2026-04-14T21:06:15.464715+00:00,,MX1304-italika-d150,Italika,D150,motoneta italika d150 blanco con azul,2026,2026,no_stock,"22,999",23999.0,23999.0,0.0,23999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p,https://www.galgo.com/mx/motos/MX1304-italika-d150
17,2026-04-14T21:06:15.464715+00:00,,MX2510-italika-dt-150,Italika,D150 LT,motoneta italika d150 lt negra,2026,2026,no_stock,"19,499",20499.0,20499.0,0.0,20499.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p,https://www.galgo.com/mx/motos/MX2510-italika-dt-150
18,2026-04-14T21:06:15.464715+00:00,,MX3411-italika-rt250-gps,Italika,RT250 GPS,motocicleta deportiva italika rt 250 con gps roja,2026,2026,available,"45,999",46999.0,46999.0,0.0,46999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-deportiva-italika-rt-250-con-gps-roja-34007114/p,https://www.galgo.com/mx/motos/MX3411-italika-rt250-gps
19,2026-04-14T21:06:15.464715+00:00,,MX2507-italika-280z,Italika,280Z,motocicleta urbana italika 280z gris,2026,2026,no_stock,"41,999",42999.0,42999.0,0.0,42999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p,https://www.galgo.com/mx/motos/MX2507-italika-280z
20,2026-04-14T21:06:15.464715+00:00,,MX3397-italika-200z-gps,Italika,200Z GPS,motocicleta italika 200z azul con gps,2026,2026,available,"37,999",38999.0,38999.0,0.0,38999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-italika-200z-azul-con-gps-34006885/p,https://www.galgo.com/mx/motos/MX3397-italika-200z-gps
21,2026-04-14T21:06:15.464715+00:00,,MX2781-italika-bit-150,Italika,BIT 150,motoneta italika bit 150 blanca con negro,2026,2026,available,"28,999",29999.0,29999.0,0.0,29999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motoneta-italika-bit-150-blanca-con-negro-34006931/p,https://www.galgo.com/mx/motos/MX2781-italika-bit-150
22,2026-04-14T21:06:15.464715+00:00,,MX2538-italika-ft200,Italika,FT 200,motocicleta de trabajo italika ft200 negra,2026,2026,available,"25,999",26999.0,26999.0,0.0,26999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p,https://www.galgo.com/mx/motos/MX2538-italika-ft200
23,2026-04-14T21:06:15.464715+00:00,,MX1309-italika-ft-125-ts,Italika,FT 125 TS,motocicleta de trabajo italika ft125 ts roja con negro,2026,2026,available,"18,999",19999.0,19999.0,0.0,19999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-ts-roja-con-negro-34005164/p,https://www.galgo.com/mx/motos/MX1309-italika-ft-125-ts
24,2026-04-14T21:06:15.464715+00:00,,MX1311-italika-ft-150-ts,Italika,FT 150 TS,motocicleta de trabajo italika ft150 ts negro con verde,2026,2026,no_stock,"20,999",21999.0,21999.0,0.0,21999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p,https://www.galgo.com/mx/motos/MX1311-italika-ft-150-ts
25,2026-04-14T21:06:15.464715+00:00,,MX1308-italika-ft-125,Italika,FT 125,motocicleta de trabajo italika ft125 negra,2026,2026,available,"17,999",18999.0,18999.0,0.0,18999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p,https://www.galgo.com/mx/motos/MX1308-italika-ft-125
26,2026-04-14T21:06:15.464715+00:00,,MX3401-italika-dm-300-gps,Italika,DM 300 GPS,motocicleta italika dm300 dorado con gps,2026,2026,available,"42,999",43999.0,43999.0,0.0,43999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-italika-dm300-dorado-con-gps-34006890/p,https://www.galgo.com/mx/motos/MX3401-italika-dm-300-gps
27,2026-04-14T21:06:15.464715+00:00,,MX2987-italika-ws-175-sport-grafito,Italika,WS 175 Sport Grafito,motoneta italika ws175 sport grafito,2026,2026,no_stock,"26,999",27999.0,27999.0,0.0,27999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p,https://www.galgo.com/mx/motos/MX2987-italika-ws-175-sport-grafito
28,2026-04-14T21:06:15.464715+00:00,,MX3410-italika-modena-175-gps,Italika,Modena 175 GPS,motoneta italika modena 175 con gps azul,2026,2026,available,"31,999",32999.0,32999.0,0.0,32999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motoneta-italika-modena-175-con-gps-azul-34006716/p,https://www.galgo.com/mx/motos/MX3410-italika-modena-175-gps
29,2026-04-14T21:06:15.464715+00:00,,MX2803-italika-vort-x-300,Italika,Vort X 300,motocicleta deportiva italika vort x 300 roja con negro,2026,2026,available,"57,999",58999.0,58999.0,0.0,58999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p,https://www.galgo.com/mx/motos/MX2803-italika-vort-x-300
30,2026-04-14T21:06:15.464715+00:00,,MX1303-italika-d125,Italika,D125,motoneta italika d125 azul con negro,2026,2026,available,"18,999",19999.0,19999.0,0.0,19999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motoneta-italika-d125-azul-con-negro-34006289/p,https://www.galgo.com/mx/motos/MX1303-italika-d125
31,2026-04-14T21:06:15.464715+00:00,,MX1338-italika-ds-150-g,Italika,DS 150,motoneta italika ds150 negra,2026,2026,no_stock,"24,999",25999.0,25999.0,0.0,25999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motoneta-italika-ds150-negra-34006307/p,https://www.galgo.com/mx/motos/MX1338-italika-ds-150-g
32,2026-04-14T21:06:15.464715+00:00,,MX2656-italika-atv190,Italika,ATV 190,cuatrimoto italika atv 190 gris,2026,2026,available,"49,999",50999.0,50999.0,0.0,50999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/cuatrimoto-italika-atv-190-gris-34006332/p,https://www.galgo.com/mx/motos/MX2656-italika-atv190
33,2026-04-14T21:06:15.464715+00:00,,MX3412-italika-vitalia-150-gps,Italika,Vitalia 150 GPS,motoneta italika vitalia 150 beige con gps,2026,2026,available,"31,999",32999.0,32999.0,0.0,32999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motoneta-italika-vitalia-150-beige-con-gps-34006773/p,https://www.galgo.com/mx/motos/MX3412-italika-vitalia-150-gps
34,2026-04-14T21:06:15.464715+00:00,,MX1314-italika-rc200,Italika,RC200,motocicleta chopper italika rc200 gris,2026,2026,no_stock,"27,999",28999.0,28999.0,0.0,28999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p,https://www.galgo.com/mx/motos/MX1314-italika-rc200
35,2026-04-14T21:06:15.464715+00:00,,MX3398-italika-250z-gps,Italika,250Z GPS,motocicleta italika 250z carbono negra con gps,2026,2026,available,"42,999",43999.0,43999.0,0.0,43999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-italika-250z-carbono-negra-con-gps-34007058/p,https://www.galgo.com/mx/motos/MX3398-italika-250z-gps
36,2026-04-14T21:06:15.464715+00:00,,MX2589-italika-tc-300,Italika,TC 300,motocicleta chopper italika tc 300 negra,2026,2026,available,"46,999",47999.0,47999.0,0.0,47999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p,https://www.galgo.com/mx/motos/MX2589-italika-tc-300
37,2026-04-14T21:06:15.464715+00:00,,MX2255-italika-sptfire-250,Italika,Sptfire 250,motocicleta cafe racer italika sptfire 250 plata,2026,2026,available,"25,999",26999.0,26999.0,0.0,26999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p,https://www.galgo.com/mx/motos/MX2255-italika-sptfire-250
38,2026-04-14T21:06:15.464715+00:00,,MX3399-italika-dm-150-gps,Italika,DM 150 GPS,motocicleta doble proposito italika dm150 con gps blanca,2026,2026,available,"27,999",28999.0,28999.0,0.0,28999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-doble-proposito-italika-dm150-con-gps-blanca-34006888/p,https://www.galgo.com/mx/motos/MX3399-italika-dm-150-gps
39,2026-04-14T21:06:15.464715+00:00,,MX3402-italika-dm-200-gps,Italika,DM 200 GPS,motocicleta doble proposito italika dm200 con gps azul,2026,2026,available,"30,999",31999.0,31999.0,0.0,31999.0,0.0,contado,MXN,,,exact,https://www.italika.mx/motocicleta-doble-proposito-italika-dm200-con-gps-azul-34006255-1300703478/p,https://www.galgo.com/mx/motos/MX3402-italika-dm-200-gps
41,2026-04-14T21:06:15.464715+00:00,,MX1314-italika-rc200,Italika,RC200,motocicleta chopper italika rc200 gris,2025,2026,available,"27,999",28999.0,28999.0,0.0,28999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motocicleta-chopper-italika-rc200-gris-34005722/p,https://www.galgo.com/mx/motos/MX1314-italika-rc200
42,2026-04-14T21:06:15.464715+00:00,,MX2507-italika-280z,Italika,280Z,motocicleta urbana italika 280z gris,2025,2026,available,"41,999",42999.0,42999.0,0.0,42999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motocicleta-urbana-italika-280z-gris-34006326/p,https://www.galgo.com/mx/motos/MX2507-italika-280z
44,2026-04-14T21:06:15.464715+00:00,,MX1304-italika-d150,Italika,D150,motoneta italika d150 blanco con azul,2025,2026,available,"22,999",23999.0,23999.0,0.0,23999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motoneta-italika-d150-blanco-con-azul-34006669/p,https://www.galgo.com/mx/motos/MX1304-italika-d150
45,2026-04-14T21:06:15.464715+00:00,,MX2987-italika-ws-175-sport-grafito,Italika,WS 175 Sport Grafito,motoneta italika ws175 sport grafito,2025,2026,available,"26,999",27999.0,27999.0,0.0,27999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motoneta-italika-ws175-sport-grafito-34006561/p,https://www.galgo.com/mx/motos/MX2987-italika-ws-175-sport-grafito
46,2026-04-14T21:06:15.464715+00:00,,MX1409-italika-rc250-2023,Italika,RC250,motocicleta chopper italika rc250 negra,2025,2026,available,"30,999",31999.0,31999.0,0.0,31999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motocicleta-chopper-italika-rc250-negra-34005813/p,https://www.galgo.com/mx/motos/MX1409-italika-rc250-2023
51,2026-04-14T21:06:15.464715+00:00,,MX2771-italika-atv-200,Italika,ATV 200,cuatrimoto italika atv200 naranja,2025,2026,available,"54,999",55999.0,55999.0,0.0,55999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/cuatrimoto-italika-atv200-naranja-34006718/p,https://www.galgo.com/mx/motos/MX2771-italika-atv-200
52,2026-04-14T21:06:15.464715+00:00,,MX2589-italika-tc-300,Italika,TC 300,motocicleta chopper italika tc 300 negra,2025,2026,available,"46,999",47999.0,47999.0,0.0,47999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motocicleta-chopper-italika-tc-300-negra-34006362/p,https://www.galgo.com/mx/motos/MX2589-italika-tc-300
53,2026-04-14T21:06:15.464715+00:00,,MX2255-italika-sptfire-250,Italika,Sptfire 250,motocicleta cafe racer italika sptfire 250 plata,2025,2026,available,"25,999",26999.0,26999.0,0.0,26999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motocicleta-cafe-racer-italika-sptfire-250-plata-34005271/p,https://www.galgo.com/mx/motos/MX2255-italika-sptfire-250
54,2026-04-14T21:06:15.464715+00:00,,MX2538-italika-ft200,Italika,FT 200,motocicleta de trabajo italika ft200 negra,2025,2026,available,"25,999",26999.0,26999.0,0.0,26999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-negra-34006715/p,https://www.galgo.com/mx/motos/MX2538-italika-ft200
55,2026-04-14T21:06:15.464715+00:00,,MX2803-italika-vort-x-300,Italika,Vort X 300,motocicleta deportiva italika vort x 300 roja con negro,2025,2026,available,"57,999",58999.0,58999.0,0.0,58999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motocicleta-deportiva-italika-vort-x-300-roja-con-negro-34004912/p,https://www.galgo.com/mx/motos/MX2803-italika-vort-x-300
56,2026-04-14T21:06:15.464715+00:00,,MX2510-italika-dt-150,Italika,D150 LT,motoneta italika d150 lt negra,2025,2026,available,"19,499",20499.0,20499.0,0.0,20499.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motoneta-italika-d150-lt-negra-34005388/p,https://www.galgo.com/mx/motos/MX2510-italika-dt-150
57,2026-04-14T21:06:15.464715+00:00,,MX1308-italika-ft-125,Italika,FT 125,motocicleta de trabajo italika ft125 negra,2025,2026,available,"17,999",18999.0,18999.0,0.0,18999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motocicleta-de-trabajo-italika-ft125-negra-34005157/p,https://www.galgo.com/mx/motos/MX1308-italika-ft-125
62,2026-04-14T21:06:15.464715+00:00,,MX1311-italika-ft-150-ts,Italika,FT 150 TS,motocicleta de trabajo italika ft150 ts negro con verde,2025,2026,available,"20,999",21999.0,21999.0,0.0,21999.0,0.0,contado,MXN,,,fallback_year,https://www.italika.mx/motocicleta-de-trabajo-italika-ft150-ts-negro-con-verde-34005332/p,https://www.galgo.com/mx/motos/MX1311-italika-ft-150-ts

In [17]:
df_final[df_final["url_scraped"].isna()]

,captured_at,previous_scrape_at,code,brand,model,model_name,year,year_scraped,status,price_scraped,price_scraped_with_galgo_fee,price_base,discount_amount,price_net,price_diff,price_type,currency,change_status,visibility,year_match_type,url_scraped,marketplace_url
40,NaN,NaN,MX2465-italika-dm-300,Italika,DM 300,NaN,2026,<NA>,available,NaN,NaN,41999.0,0.0,41999.0,NaN,NaN,NaN,NaN,NaN,fallback_year,NaN,https://www.galgo.com/mx/motos/MX2465-italika-dm-300
43,NaN,NaN,MX1318-italika-vitalia-150,Italika,Vitalia 150,NaN,2026,<NA>,no_stock,NaN,NaN,25999.0,0.0,25999.0,NaN,NaN,NaN,NaN,NaN,fallback_year,NaN,https://www.galgo.com/mx/motos/MX1318-italika-vitalia-150
47,NaN,NaN,MX1306-italika-dm-250,Italika,DM 250,NaN,2026,<NA>,no_stock,NaN,NaN,33999.0,0.0,33999.0,NaN,NaN,NaN,NaN,NaN,fallback_year,NaN,https://www.galgo.com/mx/motos/MX1306-italika-dm-250
48,NaN,NaN,MX1302-italika-atv-250,Italika,ATV 250,NaN,2025,<NA>,available,NaN,NaN,63999.0,0.0,63999.0,NaN,NaN,NaN,NaN,NaN,fallback_year,NaN,https://www.galgo.com/mx/motos/MX1302-italika-atv-250
49,NaN,NaN,MX1306-italika-dm-250,Italika,DM 250,NaN,2025,<NA>,available,NaN,NaN,35999.0,0.0,35999.0,NaN,NaN,NaN,NaN,NaN,fallback_year,NaN,https://www.galgo.com/mx/motos/MX1306-italika-dm-250
50,NaN,NaN,MX2580-italika-ft-250-gts,Italika,FT 250 GTS,NaN,2026,<NA>,available,NaN,NaN,34999.0,0.0,34999.0,NaN,NaN,NaN,NaN,NaN,fallback_year,NaN,https://www.galgo.com/mx/motos/MX2580-italika-ft-250-gts
58,NaN,NaN,MX1295-italika-250-z,Italika,250Z,NaN,2026,<NA>,no_stock,NaN,NaN,43999.0,0.0,43999.0,NaN,NaN,NaN,NaN,NaN,fallback_year,NaN,https://www.galgo.com/mx/motos/MX1295-italika-250-z
59,NaN,NaN,MX3400-italika-dm-250-gps,Italika,DM 250 GPS,NaN,2026,<NA>,available,NaN,NaN,39999.0,0.0,39999.0,NaN,NaN,NaN,NaN,NaN,fallback_year,NaN,https://www.galgo.com/mx/motos/MX3400-italika-dm-250-gps
60,NaN,NaN,MX1406-italika-titan,Italika,Titan,NaN,2025,<NA>,no_stock,NaN,NaN,50999.0,0.0,50999.0,NaN,NaN,NaN,NaN,NaN,fallback_year,NaN,https://www.galgo.com/mx/motos/MX1406-italika-titan
61,NaN,NaN,MX3084-italika-at125-grafito,Italika,AT125 Grafito,NaN,2026,<NA>,available,NaN,NaN,20999.0,0.0,20999.0,NaN,NaN,NaN,NaN,NaN,fallback_year,NaN,https://www.galgo.com/mx/motos/MX3084-italika-at125-grafito

## 9. Inspeccion

In [18]:
# Diagnostico rapido de cobertura del merge
print(df_merged["_merge"].value_counts(dropna=False))

solo_marketplace = df_merged[df_merged["_merge"] == "left_only"][["brand", "model", "year"]].drop_duplicates()
solo_scrapeado = df_merged[df_merged["_merge"] == "right_only"][["model_name", "model_mapped", "year_scraped", "url"]].drop_duplicates()

print(f"Solo marketplace: {len(solo_marketplace)}")
print(f"Solo scrapeado: {len(solo_scrapeado)}")
solo_scrapeado.head(20)

_merge
both          40
left_only     23
right_only     3
Name: count, dtype: int64
Solo marketplace: 23
Solo scrapeado: 3

,model_name,model_mapped,year_scraped,url
7,motocicleta urbana italika 280z con gps gris,280z gps,2026,https://www.italika.mx/motocicleta-urbana-italika-280z-con-gps-gris-34006887/p
9,motocicleta de trabajo italika at125 grafito,at125,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-at125-grafito-34006712/p
44,motocicleta de trabajo italika ft200 gts gris con gps,ft200 gts gps,2026,https://www.italika.mx/motocicleta-de-trabajo-italika-ft200-gts-gris-con-gps-34007052/p

In [19]:
# Filas sin codigo de inventario
df_final[df_final["code"].isna()]

Empty DataFrame
Columns: [captured_at, previous_scrape_at, code, brand, model, model_name, year, year_scraped, status, price_scraped, price_scraped_with_galgo_fee, price_base, discount_amount, price_net, price_diff, price_type, currency, change_status, visibility, year_match_type, url_scraped, marketplace_url]
Index: []

In [20]:
from datetime import date

today_str = date.today().strftime("%d%m%Y")
print(today_str)

14042026

## 10. Exportar

In [21]:
output_info = {
    "sheet_name": "[Scraping - MX] Comparativa de precios",
    "worksheet": BRAND_NAME,  # "Italika" o "Bajaj"
    "df": df_final.sort_values(by="model_name"),
}

gsheets.update_sheet(output_info, clear_data=True)
print(f"Datos escritos en '{output_info['sheet_name']}' > hoja '{output_info['worksheet']}' — {len(df_final)} filas")

Updated sheet: [Scraping - MX] Comparativa de precios
Datos escritos en '[Scraping - MX] Comparativa de precios' > hoja 'Italika' — 63 filas

## 11. Registrar diferencias en log histórico

In [22]:
from src.utils.price_diff_log import append_price_diff_log

LOG_PATH = "../data/logs/price_diff_log.csv"

rows_logged = append_price_diff_log(df_final, LOG_PATH)

if rows_logged:
    print(f"{rows_logged} modelos con diferencia de precio registrados en el log.")
else:
    print("Sin diferencias de precio en esta ejecución — nada agregado al log.")

Sin diferencias de precio en esta ejecución — nada agregado al log.

---
## Anexo: correr sobre catalogo completo

In [23]:
# # Descomentar para correr con una lista mas grande de URLs
# rows_full = run_price_tracking(
#     urls=urls_to_scrape,
#     brand_name=BRAND_NAME,
# )
# df_full = pd.DataFrame(rows_full)
# print(f"Modelos procesados: {len(df_full)}")
# print(df_full["change_status"].value_counts().to_dict())
# df_full.head()